### ISSUE TITLE
Withdrawal of OpenSSL 3.0.6 and 1.1.1r

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/openssl-feedstock#109]
### Comment:

https://mta.openssl.org/pipermail/openssl-announce/2022-October/000237.html

do not merge until new releases are made.

**Comment by jakirkham** [comment]
cc @conda-forge/openssl @conda-forge/core (for awareness)

**Comment by beckermr** [comment]
We should mark them as broken asap

**Comment by h-vetinari** [comment]
It's also important to note that they've been withdrawn for a performance regression that's not security sensitive. So not such a big deal IMO

**Comment by hmaarrfk** [comment]
I closed the one for 3.0.6 but just didn't want anybody making PRs and others not seeing the notice.

**Comment by h-vetinari** [comment]
With the releases of 3.0.7 and 1.1.1s, I'm closing this. :)
