### ISSUE TITLE
win-64_openssl-3.2.1-hcfcfb64_0\openssl.exe is possibly infected

### ISSUE THREAD

**Issue by ekomarova** [conda-forge/openssl-feedstock#150]
### Comment:

This is just a question related to how conda-forge pipelines work and how the built bits are scanned before uploading to the channel. Is there any kind of validation and virus checking, for example with mcafee or smth?

When trying to validate openssl-3.2.1-hcfcfb64_0 with mcafee, mcafee finds trojan:
```
mcafee>scan.exe "Downloads\win-64_openssl-3.2.1-hcfcfb64_0\openssl.exe" /RECURSIVE /RPTOBJECTS UNZIP /LOUD /ANALYZE /PANALYZE /RPTCOR /REPORT=report.txt
Command Line Scanner for Win64 Version: 7.0.0.370
Copyright (C) 2021 McAfee, Inc.
(408) 988-3832 EVALUATION COPY - March 15 2024

AV Engine version: 6300.9389 for Win64.
Dat set version: 11013 created Mar 14 2024
Scanning for 596817 viruses, trojans and variants.

Downloads\win-64_openssl-3.2.1-hcfcfb64_0\openssl.exe [MD5:fc026af4963bc277a812f6d0f2f3344f] ... Found the RDN/genericu trojan !!!


Summary Report on Downloads\win-64_openssl-3.2.1-hcfcfb64_0\openssl.exe
File(s)
        Total files:...................     1
        Total Objects:.................     1
        Clean:.........................     0
        Not Scanned:...................     0
        Possibly Infected:.............     1
        Objects Possibly Infected:.....     1
```

**Comment by ekomarova** [comment]
I also want to point out previous versions are clean and don't have this problem

**Comment by beckermr** [comment]
We do not have the resources to do the scanning of the kind you are asking about. 

I have marked this version broken and am rotating the tokens associated with this feedstock.

**Comment by h-vetinari** [comment]
I think it's exceedingly unlikely that someone managed to sneak a change into the git history that maliciously injects a Trojan but is not visible in the git history, the logs, etc.

The build we do is from source with a very vanilla build setup, so it's _far_ more likely that this is a false positive from McAfee.

**Comment by h-vetinari** [comment]
> I have marked this version broken

Worth noting that this was reverted in https://github.com/conda-forge/admin-requests/pull/964.

Quoting my response from there for context:
> This was almost certainly a false positive from McAfee (also wouldn't be the first time in cryptography-related projects). I don't see a plausible way of either a Trojan in openssl itself, or someone who can corrupt our build process completely unnoticed.
> 
> Also, the build has been live for a long time.

**Comment by xaleryb** [comment]
As for today we have already 2 more scans reported problems on 3.2.1 version. But 3.2.0 at the same time has clean report.

Do you have any official conclusion we may use to be sure that is a false-positive report?

![scan for openssl 3 2 1](https://github.com/conda-forge/openssl-feedstock/assets/38352652/1257e4b0-9258-4ea7-b747-60468dc8cec9)

**Comment by AndresGuzman-Ballen** [comment]
I appreciate the civility of this conversation. I won't link to it, but I came across a completely unrelated GitHub ticket (has nothing to do with conda-forge) pointing out a possible infection to a codebase and the reply from the maintainer owner was, how should I put it, as rude as a person can be LOL

**Comment by h-vetinari** [comment]
> Do you have any official conclusion we may use to be sure that is a false-positive report?

The "official" conclusion is that McAfee has a [history](https://forums.mcafee.com/t5/VirusScan/False-Positive-Detection/td-p/697779) of false positives in crypto-related projects, and while those are clear bugs in the virus detection mechanism, McAfee generally cares very little about fixing them (because throwing warning shows it's doing something).

We use the original upstream sources, validated by hash of the archive, with only the build infrastructure having the rights to upload packages. No plausible scenario for corruption of this process has been proposed.

In the interest of moving forward, I've triggered a rebuild in #151 - if the scan of the resulting package still shows a warning, we can consider the false positive reproduced. At that point you can talk to McAfee to not produce warnings on the most widely used open source cryptography software in the world.

**Comment by ekomarova** [comment]
After scanning the new build, mcafee no longer finds trojan. So probably previous build really could have been infected. Thanks for rebuilding!

**Comment by h-vetinari** [comment]
Glad to hear the warning went away. This still doesn't mean the previous build was infected (McAfee could have fixed the false positive in the meantime, or it was non-deterministic, or ...). That said, if people want to remove the older build out of an abundance of caution, I won't object. The good thing is that conda aggressively updates openssl on any environment interaction, so the `_0` builds will soon be replaced anyway.
