### ISSUE TITLE
Upgrade to openssl 1.0.2p

### ISSUE THREAD

**Issue by collinsethans** [conda-forge/openssl-feedstock#23]
Current release is 1.0.2o. A latest version is available (and also on anaconda). Please update.

**Comment by jakirkham** [comment]
Would it be possible to get automatic updates for this, @CJ-Wright?

In the near term, would you be willing to do a PR, @collinsethans?

**Comment by collinsethans** [comment]
@jakirkham I don't think I will be able to do a PR -- I am just new to conda and thus came to conda-forge.

I also just found that there's 1.1.0 openssl releases -- latest being 1.1.0i.

**Comment by CJ-Wright** [comment]
Maybe, I'll need to look at the graph to see what is going on.

**Comment by CJ-Wright** [comment]
It seems the bot can't find an upstream version. I'm not certain why that is.

**Comment by collinsethans** [comment]
@jakirkham @jjhelmus @CJ-Wright Can this be resolved and released?

**Comment by CJ-Wright** [comment]
I don't think the bot not finding the upstream is a blocking issue here.
