### ISSUE TITLE
openssl 1.1.1 considered newer than 1.1.1a by conda

### ISSUE THREAD

**Issue by msarahan** [conda-forge/openssl-feedstock#29]
conda obeys PEP440 regarding versioning.  OpenSSL does not.  They start from 1.1.1 and 1.1.1a is the next version.  Conda thinks 1.1.1a is a lower version.

If 1.1.1 is available, conda will prefer it to 1.1.1a.  For defaults, we removed 1.1.1 so that 1.1.1a would get picked up.  Long-term, we will special-case openssl in conda.

@isuruf recommended potentially using epoch instead:

```
Isuru Fernando @isuruf 15:24
@msarahan, why not increase the epoch instead of removing 1.1.1?

Mike Sarahan @msarahan 15:25
what would the spec look like? I'm just not used to using epochs for anything

Isuru Fernando @isuruf 15:25
version = 1!1.1.1a
1.1.1 = 0!1.1.1 < 1!1.1.1a
```

**Comment by hmaarrfk** [comment]
If we skip release 1.1.1 does that fix things??? ;)
