### ISSUE TITLE
Error: old string incorrect `:�' when linking

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/openssl-feedstock#3]
```
Linking packages ...
Error: old string incorrect `:�'                                                                                                                        |   0%
Error: post-link failed for: conda-forge::openssl-1.0.2h-0
```

This was when running `conda skeleton`. I can't reproduce it outside of that.

**Comment by jakirkham** [comment]
No clue. I don't think we even have post-link scripts for `openssl` or its dependencies. `conda info`?

**Comment by asmeurer** [comment]
So I recently moved `conda-forge` above `defaults`. I think maybe what happened is it thought it was using the conda-forge openssl, but it was really using the one from defaults in my cache. The one in defaults does use a post-link script, to support older versions of conda that don't support binary prefix relocation.

I don't understand why this would result in this crash, though.

**Comment by jakirkham** [comment]
We ran into this earlier today when doing a Heroku deployment. Not really sure why this is happening as there are no post-link steps in our `openssl` package or in the feedstock FWICT.

cc @pelson

**Comment by asmeurer** [comment]
But the `defaults` openssl does have one. So somehow it is getting called instead.

**Comment by jakirkham** [comment]
Asking @msarahan about it to see if he has any ideas.

**Comment by asmeurer** [comment]
Based on `strings ~/anaconda/pkgs/openssl-1.0.2h-1/bin/.openssl-libcrypto-fix`, the error is indeed coming from the `defaults` post-link (and that exact error string isn't in conda).

**Comment by jakirkham** [comment]
Ran into a case of this in a CI [build]( https://travis-ci.org/jakirkham/metawrap/jobs/153332436#L307-L309 ). Hopefully this helps narrow it down more.

**Comment by msarahan** [comment]
Sorry, I've got nothing on this.  Like @asmeurer suggested, I suspect caching misbehavior, particularly if the build strings are identical.  It may be beneficial to start adding "cf" to all of our build strings to prevent this from happening.  I'm not sure if @mcg1969 might have better ideas.

CC'ing @kalefranz as Conda lead - this is more his area.

**Comment by jakirkham** [comment]
> It may be beneficial to start adding "cf" to all of our build strings to prevent this from happening. I'm not sure if @mcg1969 might have better ideas.

Probably would work, but it is going to be pretty kludgy adding that everywhere. I hope we can do much better than that.

**Comment by jakirkham** [comment]
Created a simple reproducer. Building this [`Dockerfile`]( https://github.com/jakirkham/docker_link_openssl_err/blob/7868da882bebbf82becf568cf8e9a09e54a3fe99/Dockerfile ) will generate the error everytime. An example build showing this failure can be seen on [Quay]( https://quay.io/repository/jakirkham/link_openssl_err/build/cb33f729-ebb2-476c-96f0-1488789462b4 ).

**Comment by jakirkham** [comment]
Raising as issue ( https://github.com/conda/conda/issues/3319 ).

**Comment by kalefranz** [comment]
Yeah I think this is probably a pretty ugly conda bug.

**Comment by frol** [comment]
Upgrading Conda from 4.2.9 to 4.2.11 solved the issue for me.

**Comment by jakirkham** [comment]
This was an issue with `defaults` (i.e. not a `conda-forge` issue), which I *believe* has been resolved. Going to close this out.
