### ISSUE TITLE
use nasm?

### ISSUE THREAD

**Issue by carlodri** [conda-forge/openssl-feedstock#30]
it looks like `nasm` is the only supported assembler:

https://github.com/openssl/openssl/blob/9a3b5b766421b7ed9df859956d44fcbe52c2dd82/NOTES.WIN#L50-L54

is there a reason for using `yasm` here? Very likely yes (I imagine), but just wanted to check.

**Comment by jjhelmus** [comment]
yasm is a full rewrite of nasm that is fully compatible.  The comment in the NOTES file most likely is directed at MASM, the assembler from Microsoft.  That said I have no problem switching the recipe to using nasm.

**Comment by msarahan** [comment]
in openssl 1.1.1, Anaconda switched to nasm.  Yasm didn't work.

**Comment by carlodri** [comment]
we could give a shot to `nasm` then, I also read somewhere that it is more actively maintained.

**Comment by jakirkham** [comment]
Both assemblers work and are pretty much (if not exactly) drop-in replacements of each other. IIRC OpenSSL recommends using NASM at this point (if they haven’t always). Also NASM has been better maintained of late.

**Comment by carlodri** [comment]
@jakirkham will do!
