### ISSUE TITLE
policy for version release

### ISSUE THREAD

**Issue by carlodri** [conda-forge/openssl-feedstock#32]
We should probably agree on a version release plan here. Currently we are on the 1.0.2 series, whereas also 1.1.0 and 1.1.1. have been released. 

How should we handle releases here? Since the build requirements seems to change from 1.0.2 to 1.1.1, probably it would be best to maintain a branch for each series.

How should we handle #29 across these branches? We could probably use some hacky epoch trick, but ~I'm not sure what is best (_i.e._ like `1020!1.0.2p`, `1021!1.0.2q`?)~ at the moment I can't imagine how.

Let me know you thoughts!

**Comment by jjhelmus** [comment]
I think we should jump to 1.1.1a, skipping 1.1.0 and 1.1.1 entirely.  As long as 1.1.1 is never built, #29, never comes into play.  

It will be necessary to maintain 1.0.2 for some time as everything downstream that links against OpenSSL will need to be rebuilt for the 1.1.1 release.  This would be a good task for the update bot.

**Comment by hmaarrfk** [comment]
Is Open SSL continuing to maintain 1.0?

**Comment by carlodri** [comment]
yup, 1.0.2 will be there until the end of this year (see https://www.openssl.org/policies/releasestrat.html)

**Comment by hmaarrfk** [comment]
ok sure, lets createa branch for it.

**Comment by carlodri** [comment]
let me recap: I will create a `1.0.2` branch and leave it there for future patch releases and we continue pushing the `1.1.1` series on `master`, ok?

**Comment by hmaarrfk** [comment]
Sounds good.
