### ISSUE TITLE
version numbering for openssl (e.g. 1.1.1b) causes problems with conda 4.6.*

### ISSUE THREAD

**Issue by xylar** [conda-forge/openssl-feedstock#40]
Similarly to [esmf-feedstock](https://github.com/conda-forge/esmf-feedstock/issues/35), the non-standard version names used by `openssl` are causing trouble in the latest version of conda because the letter is treated as an alpha or beta identifier and versions with such an identifier are ignored in comparison operators.  For example, `1.1.1b` fails the test: `openssl[version='>=1.1.1,<1.1.2a']`.

For `esmf`, the chosen solution was to drop the non-standard letter.  For `openssl`, the choice is not as clear.

**Comment by xylar** [comment]
@ocefpaf, this is another case where your input would be appreciated, given the help you gave me with https://github.com/conda-forge/esmf-feedstock/issues/35

**Comment by xylar** [comment]
I think I'm going to close this issue.  It turns out to be unrelated to the package version conflicts I experienced with another package last night.  Also, unlike the case of `esmf`, all versions of `openssl` have letters so they can be compared in the expected way (e.g. `1.1.1a < 1.1.1b < 1.1.2a`).

**Comment by ocefpaf** [comment]
> @ocefpaf, this is another case where your input would be appreciated, given the help you gave me with [conda-forge/esmf-feedstock#35](https://github.com/conda-forge/esmf-feedstock/issues/35)

The version problem is similar but `openssl` is tightly so only one specific version should be used with our stack. At the moment we are rebuilding the stack to use `1.1.1a` but `1.0.2` should still be the "stable" one from the latest pinning.

PS: if you are forcing different versions be careful b/c the packages may not work properly. Ideally one should not need to force a version of `openssl`, just let the latest pinned one be pulled with the rest of the stack.

**Comment by xylar** [comment]
@ocefpaf, thanks for the explanation.  I think the problem came for me when trying to pin a specific python version as part of a metapackage, but I have no idea which dependency brought it an incompatible version of `openssl`.  It isn't any of the packages I explicitly specified.  In any case, it seems as if the problem goes away if I don't explicity pin the python version so I'm not going to investigate further for now.

**Comment by ocefpaf** [comment]
It may be a problem with the current `openssl` migration, which has not finished yet. I'm pinging @CJ-Wright here for some insight.

**Comment by CJ-Wright** [comment]
Python has an openssl dep if memory serves. What python are you pinning to?

**Comment by xylar** [comment]
I was pinning to python 3.7.  Do you know which version of openssl that's pinning to?

**Comment by CJ-Wright** [comment]
Ah did your env pull in Qt? We have a few feedstocks which haven't been rebuilt with the new openssl listed here: https://conda-forge.org/status/ If you pulled in any of those in PR, awaiting PR, or awaiting parents then that could cause some issues.

**Comment by xylar** [comment]
It's certainly possible.  I'll keep an eye on that page if/when I run into this problem again.  Thanks for helping me understand the issue.
