### ISSUE TITLE
Windows package seems not including libeay32.dll

### ISSUE THREAD

**Issue by igortg** [conda-forge/openssl-feedstock#44]
openssl package ver. 1.1.1b seems not including libeay32.dll.

ver 1.0.2p seems working just fine.

@hmaarrfk, do you have any guess on why DLLs are not being copied?

**Comment by hmaarrfk** [comment]
It seems that the lines that would have copied those files are commented out.

I mostly copied the recipe from defaults. My commit say that I did a blind sync at that step
@msarahan seems to have worked on that aspect, not sure if he can weigh in.

**Comment by msarahan** [comment]
1.1.1 has totally different library names.  I don't think there is any libeay32.dll file anymore.

**Comment by jjhelmus** [comment]
OpenSSL 1.1.0 changed the libraries names as follows:

libeay32.dll -> libcrypto.dll
ssleay32.dll -> libssl.dll

see curl/curl#984

**Comment by igortg** [comment]
I should had investigated further. Thks guys and sorry about that
