### ISSUE TITLE
Split out static libraries

### ISSUE THREAD

**Issue by jcrist** [conda-forge/openssl-feedstock#45]
The static libraries are non-negligible in size:

```
$ du -hc lib/libssl.a lib/libcrypto.a
776K    lib/libssl.a
4.1M    lib/libcrypto.a
4.8M    total
```

If possible, it would be useful to split out the static libraries into separate packages (especially important for installation in a docker container).

**Comment by jjhelmus** [comment]
I'm in favor of spitting out the static libraries but this does open up the question of how best to split this package.  The current openssl package contains a number of files.  

* The openssl and c_rehash binaries
* Shared libraries
* Static libraries
* Include files
* Configuration files

These could be split into a number of packages.  For example one could imagine 4 packages:
* `libopenssl` which contains the shared libraries
* `libopenssl-static` which contains the static libraries
* `libopenssl-dev` which contains the include files and the `.pc` configuration files.
* `openssl` which contains the the binaries and other relevant configuration files. 

This level of splitting would be quite disruptive as all packages which currently depend on `openssl` as a run or host dependency would need to determine if they need to depend on `libopenssl` or `openssl` and potentially add `openssl-dev` as a host dependency.

A less disruptive change would be to create two packages, `libopenssl-static` with the static libraries and `openssl` with all other files.  Does this seem reasonable?

**Comment by jcrist** [comment]
> A less disruptive change would be to create two packages, `libopenssl-static` with the static libraries and `openssl` with all other files. Does this seem reasonable?

I *think* so, but I can't say for certain. My main goal here is to make it so default naive use minimizes the amount of unnecessary files downloaded. I don't care if a few unnecessary files leak through (like the configuration files), as long as the common large offenders are taken care of. I suspect that users who really really care about minimal disk usage will always need to hand tune.

**Comment by ocefpaf** [comment]
> A less disruptive change would be to create two packages, `libopenssl-static` with the static libraries and `openssl` with all other files. Does this seem reasonable?

:+1:
