### ISSUE TITLE
Recipe outputs: openssl and libopenssl-static

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/openssl-feedstock#51]
The `install_openssl.sh` scripts ends with 

```
# remove the static libraries
rm ${PREFIX}/lib/libcrypto.a
rm ${PREFIX}/lib/libssl.a
```

which are only installed with the `libopenssl-static` output. However, this output cannot be used alone because it does not provide the OpenSSL headers.

I think that it may be preferable to not split the package in two outputs.

**Comment by SylvainCorlay** [comment]
cc @jjhelmus it seems that you made that split deliberately (or ported the anaconda recipe which was making the split).

**Comment by jjhelmus** [comment]
See this discussion in #45 where this exact concern was discussed.

**Comment by SylvainCorlay** [comment]
Thanks for the context @jjhelmus.

I am curious about how linux distributions do a better split.

**Comment by jjhelmus** [comment]
Debian [builds four packages from the openssl source](https://packages.debian.org/source/stable/openssl).  They are as follows:

* libssl1.1 : The openssl shared libraries, libssl and libcrypto
* libssl-doc : documentation
* libssl-dev : development files, headers, pkgconfig files and the static libraries
* openssl : the openssl binrary and user man pages, depends on libssl1.1

There are also two udeb packages but those are just stripped down versions of the corresponding deb packages.

**Comment by slel** [comment]
For context see also this blog post, and especially
"static libraries", the second item in "step 4".

- Jim Crist-Harif. Smaller Docker images with Conda. 2019-06-03.
  https://jcristharif.com/conda-docker-tips.html

**Comment by jjhelmus** [comment]
I do not seem any reason to rejoin these two outputs.  Feel free re-open this issue if there is still concerns about how openssl is current split.
