### ISSUE TITLE
undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b errors

### ISSUE THREAD

**Issue by ngam** [conda-forge/openssl-feedstock#80]
ref: https://github.com/conda/conda/issues/10241

I came across this problem recently and it was caused by resetting LD_LIBRARY_PATH (so that tensorflow from PyPI can find cudatoolkit from conda-forge --- is there an alternative solution btw? I know I can just load system cudatoolkits, etc. but just wondering)

Anyway, as explained in https://github.com/conda/conda/issues/10241, maybe we should consider adding those patches unless they break other systems? I am not that informed about this, hence opening the issue here for the maintainers to figure it out (or maybe it's already been discussed? idk)

---

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jakirkham** [comment]
Would using [tensorflow from conda-forge]( https://github.com/conda-forge/tensorflow-feedstock ) be an option?

**Comment by ngam** [comment]
> Would using [tensorflow from conda-forge](https://github.com/conda-forge/tensorflow-feedstock) be an option?

I am well aware of that option, but sadly not at this point --- though hopefully we can get that feedstock back on track sooner rather than later. It's silly to say this out loud, but recently I was surprised that some code I wrote was strictly speaking 2.7.0.

Anyway, tensorflow was just the side topic here (there are some system-oriented fixes, e.g. loading cudatoolkit from the system, etc. or just unsetting and resetting LD_LIBRARY_PATH every time ssh or whatever is needed) --- I imagine this would be caused by a variety of other issues potentially. 

The point is: Are we planning to add these patches or could they potentially break something elsewhere?

**Comment by ngam** [comment]
(Fwiw on the HPC system I've been using `module load cudatoolkit/xyz` sets LD_LIBRARY_PATH to some cuda-related path, so I am not really sure if there is any way around this tensorflow gimmick... I am not aware of cudatoolkit on PyPI 😄)

**Comment by jakirkham** [comment]
Referring to this comment ( https://github.com/conda/conda/issues/10241#issuecomment-876314011 )?

I'm not sure. That's probably a larger discussion.

cc @conda-forge/core

**Comment by ngam** [comment]
Yes, that comment seems to be informed. It's a wildly weird problem to have tbh... this potentially can come up in many situations where the openssl conda-forge ships conflicts in this way with what other systems ship. However, it's really unclear to me if adding these patches can potentially cause even bigger headaches on other systems (that don't have those specific patches)...
