### ISSUE TITLE
Branch for 1.1.1 to capture missing releases

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/openssl-feedstock#82]
I realized that conda-forge is two releases behind for 1.1.1 (due to the default bot behaviour treating only the newest release), including the latest CVE fix in 1.1.1n, see e.g. [here](https://www.openssl.org/news/openssl-1.1.1-notes.html).

This should IMO be fixed with higher-than-usual urgency, not least since large swaths of conda-forge are still bound to `openssl <3` due to https://github.com/conda-forge/cryptography-feedstock/pull/80.

Could someone from @conda-forge/core create a branch for 1.1.1 at 26f7bd0059d2415ec5ac962d4906127d4c557de0? If people prefer a PR to join as maintainer (and then creating the branch myself), I can do that too.

**Comment by jakirkham** [comment]
Wouldn't we want the branch here ( https://github.com/conda-forge/openssl-feedstock/commit/6b7ca60c39ceb6a1df795cd1978a30487373e75a )? That looks like the last set of changes before `3.0.0`

**Comment by h-vetinari** [comment]
Ah yes, thanks for that, I took a wrong turn in the commit history.

**Comment by jakirkham** [comment]
No worries. Have created the branch.

**Comment by h-vetinari** [comment]
Thanks. I raised #83, but this seems to be running into a fresh conda-build issue. 😑

**Comment by h-vetinari** [comment]
Branch has been created, so closing this. Still need to merge #83 though 😅
