### ISSUE TITLE
openssl=3.0.2 is nearly empty

### ISSUE THREAD

**Issue by xhochy** [conda-forge/openssl-feedstock#87]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The content of `openssl-3.0.2-pl5321h5eb16cf_0` is nearly nothing and thus it breaks a lot:

```
./ssl
./ssl/misc
./ssl/misc/tsget
./ssl/misc/tsget.pl
./ssl/misc/CA.pl
./ssl/ct_log_list.cnf
./ssl/openssl.cnf.dist
./ssl/openssl.cnf
./ssl/ct_log_list.cnf.dist
./.DS_Store
./info
./info/test
./info/test/run_test.sh
./info/licenses
./info/licenses/LICENSE.txt
./info/recipe
./info/recipe/install_openssl.sh
./info/recipe/parent
./info/recipe/parent/install_libopenssl-static.bat
./info/recipe/parent/install_openssl.bat
./info/recipe/parent/install_openssl.sh
./info/recipe/parent/bld.bat
./info/recipe/parent/build.sh
./info/recipe/parent/meta.yaml
./info/recipe/parent/install_libopenssl-static.sh
./info/recipe/conda_build_config.yaml
./info/recipe/meta.yaml
./info/run_exports.json
./info/paths.json
./info/no_link
./info/hash_input.json
./info/files
./info/about.json
./info/index.json
./info/git
```

### Installed packages

```shell
openssl-3.0.2-pl5321h5eb16cf_0
```

### Environment info

```shell
Manually inspected the package.
```

**Comment by xhochy** [comment]
This seems limited to the `osx-64`, all other look fine.

**Comment by jakirkham** [comment]
cc @h-vetinari

**Comment by jakirkham** [comment]
To summarize `bin`, `include`, and `lib` are all missing. Only the `ssl` directory made it in.

Can compare this to `linux-64/openssl-3.0.2-h166bdaf_0.tar.bz2`, which has these.

**Comment by h-vetinari** [comment]
Apologies for the breakage. There were no changes regarding osx in #84 except: https://github.com/conda-forge/openssl-feedstock/pull/84/commits/726bb6acd6e78f3b9b57aadb933f050e7c460ab2 + https://github.com/conda-forge/openssl-feedstock/pull/84/commits/82c34a9d807967c94190cfba1935e5738c620d80

So I don't really understand what's happening there.

Could adding the feedstock name (https://github.com/conda-forge/openssl-feedstock/pull/84/commits/b782a95a8b911329922dcd96ba9ce72d10d448ed) have broken something?

**Comment by xhochy** [comment]
My current suspicion is that there is some misbehaviour because `$PREFIX/lib` is non-existent.

**Comment by isuruf** [comment]
https://github.com/conda-forge/openssl-feedstock/pull/88

**Comment by h-vetinari** [comment]
Thanks a lot Isuru!

**Comment by jakirkham** [comment]
Looks like Isuru beat me to it, but will go ahead and include this comment for completeness.

We can see in [the CI log]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=480072&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=6039 ) that things are being installed. So it seems like `conda-build` is excluding them.

**Comment by jakirkham** [comment]
The broken packages have been removed.

Also a fix has been included with Isuru's PR ( https://github.com/conda-forge/openssl-feedstock/pull/88 ), which just merged. New packages should build and publish soon.

Would be good if someone here checks the new packages out (once they are up) and makes sure there are no new or lingering issues.

**Comment by jakirkham** [comment]
Looks like new packages are up

**Comment by jakirkham** [comment]
AFAICT the new packages seem to be including things as we expect (we also added a test to the recipe to this effect). Going to close this out as resolved. Though please feel free to reopen if needed
