### ISSUE TITLE
Sync with AnacondaRecipes?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/openssl-feedstock#91]
I'd like to sync the 3.0.0 branch with https://github.com/AnacondaRecipes/openssl-feedstock/, not least to finally get cryptography built with openssl 3.0.0, since I saw that Anaconda got that working, and we haven't (c.f. #76).

I [asked](https://github.com/AnacondaRecipes/openssl-feedstock/pull/8#issuecomment-1080455448) on that feedstock because AFAICT the sources for building 3.0.0 are actually not public (yet?), but perhaps the message got lost due to bad visibility (i.e. closed PRs not showing up in various cockpits/dashboards).

Could the anaconda folks publish their 3.0.0 branch somewhere? I can then sync this with the repo here.

CC @skupr-anaconda @varlackc @chenghlee @tobijk @jezdez

**Comment by hmaarrfk** [comment]
I don't see a 3.0.0 branch there.

**Comment by chenghlee** [comment]
Anaconda has not started the migration to OpensSL 3.0 yet.

**Comment by h-vetinari** [comment]
Closing this issue as outdated.
